			<?php
				$e_age = explode( ',', $sm['user']['s_age'] );
				$age = $e_age[2];
			?>
			<script>
			url = "meet";
			</script>            
			<div class="col s8 real fix-width-content" style="padding-right: 10px;" id="site-content">
                <div class="post-btn-right" data-url="search"><i class="mdi-content-filter-list"></i> <?= $sm['lang'][106]['text']; ?></div>
                <div class="post-btn-right-close"><i class="mdi-content-clear"></i></div>                
                <div class="profile-menu ">
                    <ul>
                        <li class="selected" id="allusers" data-action="allusers" >
                            <?= $sm['lang'][107]['text']; ?>
                        </li>                           
                        <li data-action="online" id="onlineusers" >
                           <?= $sm['lang'][108]['text']; ?>
                        </li>           
                    </ul>
                </div>
                <div class="search-post animated fadeIn">
					<div class="coll">
					  <div class="search-title"><?= $sm['lang'][394]['text']; ?></div>
					  <div class="radio">
						<input id="radio-1" name="radio" type="radio" checked>
						<label for="radio-1" class="radio-label"><?= $sm['lang'][388]['text']; ?></label>
					  </div>
					  <div class="radio">
						<input id="radio-2" name="radio" type="radio">
						<label  for="radio-2" class="radio-label"><?= $sm['lang'][389]['text']; ?></label>
					  </div>
					  <div class="radio">
						<input id="radio-3" name="radio" type="radio">
						<label  for="radio-3" class="radio-label"><?= $sm['lang'][390]['text']; ?></label>
					  </div>					  
					</div>
					<div class="coll" style="padding-left:25px">
					  <div class="search-title"><?= $sm['lang'][109]['text']; ?> </div>
					     <select class="input input--sm" id="meet_filter_gender"  name="radio" style="margin-top:-5px;width: 90%">
						<?php
							$all = count($sm['genders']);
							$all = $all + 1;
							foreach($sm['genders'] as $entry){
								if($entry['id'] == $sm['user']['s_gender']){
									echo '<option value="'.$entry['id'].'" selected style="color:#000;">'.$entry['text'].'</option>';
								} else {
									echo '<option value="'.$entry['id'].'" style="color:#000;">'.$entry['text'].'</option>';
								}
							}
						?>
						<option value="<?= $all; ?>" <?php if($all == $sm['user']['s_gender']){ echo 'selected'; } ?> style="color:#000;"><?= $sm['lang'][531]['text']; ?></option>			
					   </select>
					  <div class="search-title" style="margin-top:2px;margin-bottom:10px"><?= $sm['lang'][300]['text']; ?></div>					  
					  <div id="slider-range-age1"><?= $e_age[0]; ?></div>	
					  <div id="slider-range"></div>	
					  <div id="slider-range-age2"><?= $e_age[1]; ?></div>						  
					</div>					
					<div class="coll" style="padding-left:25px">
					  <div class="search-title"><?= $sm['lang'][387]['text']; ?></div>
					    <input  type="" class="search-filter-input" id="loc" value="<?= $sm['user']['city']; ?>" style="top:-5px;" />
						<input type="hidden" name="city" id="locality" value="<?= $sm['user']['city']; ?>" />
						<input type="hidden" name="country" id="country" value="<?= $sm['user']['country']; ?>"  />
						<input type="hidden" name="lat" id="lat" value="<?= $sm['user']['lat']; ?>"  />
						<input type="hidden" name="lng" id="lng" value="<?= $sm['user']['lng']; ?>"  />					  
					  <div class="search-title" style="margin-top:4px;" id="slider-distance"><?= $sm['lang'][391]['text']; ?></div>
					  <div id="slider-range2" style="top:2px"></div>							  
					</div>						
					<div class="search-btn-ok" data-filter>
						<?= $sm['lang'][385]['text']; ?>
					</div>	
					<div class="search-btn-cancel" data-close-filter >
						<?= $sm['lang'][386]['text']; ?>
					</div>
					  <input type="hidden" value="0" id="meet_filter_online" data-filter="meet_filter_online"/>
					  <input type="hidden" value="0" id="meet_filter_limit" data-filter="meet_filter_limit"/>						
                </div>
                <div class="wall" > 
                	<?php if($sm['user']['premium'] == 0){ ?>
					<div class="banner-container banner-container--wide js-banner-slot" style="margin: 0; width: 105%;margin-left:-5%;">
					    <div class="banner banner--spp js-banner-wrap" >
					        <div class="banner-content" >
					            <div class="banner-promo" >
					                <div class="brick-group brick-group--promo">
					                    <div class="brick brick--lg brick--stroke">
					                        <div class="brick-img profile-photo" data-src="<?= randomPhotoUser($sm['user']['s_gender']); ?>"></div>
					                    </div>
					                    <div class="brick brick--lg brick--stroke">
					                        <div class="brick-img profile-photo" data-src="<?= $sm['user']['profile_photo']; ?>"></div>
					                        <mark class="brick brick--xsm brick--spp brick--bc"><img src="<?= $sm['config']['theme_url']; ?>/images/vip_y.png" width="16px" /></mark>
					                    </div>
					                    <div class="brick brick--lg brick--stroke">
					                        <div class="brick-img profile-photo" data-src="<?= randomPhotoUser($sm['user']['s_gender']); ?>"></div>
					                    </div>
					                </div>
					            </div>
					            <div class="banner-text"><?= $sm['lang'][453]['text']; ?>!</div>
					        </div>
					        <div class="banner-buttons" onClick="goTo('premium');">
					            <div class="btn btn--sm btn--spp js-promo-btn"> <span class="btn-txt"><?= $sm['lang'][433]['text']; ?>!</span></div>
					        </div>
					    </div>
					</div>
					<?php } ?>                    
					<div id="meet_section" style="min-height: 400px"></div>
				    <div class="footer-badoo" style="margin-top:55px;left:-4.15%;width:104%;">
				<center>
					<div class="ad-zone">
						<?php echo siteConfig('ads'); ?>
					</div>
					<div class="download-apps">
						<h3><?= $sm['lang'][434]['text']; ?>:</h3>
						<a href="<?php echo $app_ios; ?>">
							<img src="<?php echo $sm['config']['theme_url']; ?>/images/ios.png" />
							<h2><?= $sm['lang'][435]['text']; ?></h2>
						</a>
						<a href="<?php echo $app_android; ?>">
							<img src="<?php echo $sm['config']['theme_url']; ?>/images/android.png" /><h2><?= $sm['lang'][436]['text']; ?></h2>
						</a>
					</div>
					<div class="bottom-left">
						<a href="<?php echo $sm['config']['site_url']; ?>/terms"><h3><?= $sm['lang'][437]['text']; ?></h3></a> <a href="<?php echo $sm['config']['site_url']; ?>/privacy"><h3><?= $sm['lang'][63]['text']; ?></h3></a> <a href="mailto:<?php echo $sm['config']['email']; ?>"><h3><?= $sm['lang'][64]['text']; ?></h3></a> <h3>  <?php echo $sm['config']['name']; ?> 2018 </h3>
					</div>			
				</center>
				  </div>					
                </div>
            </div> 