			<script>
			url = "credits";
			</script>            

            <div class="col s8 real fix-width-content" id="site-content" >              

                <div class="wall" style="height:100%;"> 

                    <div class="payment-promo" style="margin-top: 40px;">

    <div class="payment-promo__content"><center>

        <h5><?= $sm['lang'][503]['text']; ?>: <span class="popularity-status popularity-status--low"><?= $sm['lang'][504]['text']; ?></span></h5>

        <p class="payment-promo__txt"> <?= $sm['lang'][505]['text']; ?> <?= $sm['user']['city']; ?> <?= $sm['lang'][506]['text']; ?>… </p>

        <div class="popularity-lines">

            <div class="popularity-line js-popularity-promo-block" data-popularity-promo-block-type="1">

                <div class="left popularity-col">

                    <h1 class="popularity-col__title"><?= $sm['lang'][507]['text']; ?></h1>

                    <p> <?= $sm['lang'][508]['text']; ?>! </p>

                    <div class="btn btn--riseup" onclick="showRiseUp();"> <span class="btn-txt"><?= $sm['lang'][509]['text']; ?>!</span></div>

                </div>

                <div class="popularity-col">

                    <div class="popularity-col__img popularity-col__img--riseup popularity-col__img--male">

                        <div class="popularity-col__user-photo profile-photo" data-src="<?= randomPhoto($sm['user']['id']); ?>"></div>

                    </div>

                </div>

            </div>

            <div class="popularity-line js-popularity-promo-block" data-popularity-promo-block-type="10">

                <div class="left popularity-col">

                    <h1 class="popularity-col__title"><?= $sm['lang'][510]['text']; ?></h1>

                    <p> <?= $sm['lang'][511]['text']; ?> <b><?= $sm['lang'][512]['text']; ?>!</b> </p>

                    <div class="btn btn--encounters" onclick="showDiscover();"> <span class="btn-txt"><?= $sm['lang'][513]['text']; ?>!</span></div>

                    <!--control type: tnc-->

                    <div class="popularity-col__cost js-service-cost js-control js-core-events-container hidden">

                        <div class="service-cost">

                            <p class="service-cost__text"> </p>

                        </div>

                    </div>

                </div>

                <div class="popularity-col">

                    <div class="popularity-col__img popularity-col__img--meets">

                        <div class="popularity-col__user-photo">

                            <div class="popularity-col__user-photo_">

                            <img class="profile-photo" src="<?= randomPhoto($sm['user']['id']); ?>"></div>

                        </div>

                        <div class="brick brick--lg brick--stroke popularity-col__others popularity-col__others--1">

                            <div class="brick-img"><img src="<?= randomPhotoUser($sm['user']['s_gender']); ?>" alt=""></div>

                            <mark class="brick brick--xsm brick--like brick--stroke"><i class="icon icon--white ion-heart" style="font-size: 17px"></i></mark>

                        </div>

                        <div class="brick brick--lg brick--stroke popularity-col__others popularity-col__others--2">

                            <div class="brick-img"><img src="<?= randomPhotoUser($sm['user']['s_gender']); ?>" alt=""></div>

                            <mark class="brick brick--xsm brick--like brick--stroke"><i class="icon icon--white ion-heart" style="font-size: 17px"></i></mark>

                        </div>

                        <div class="brick brick--lg brick--stroke popularity-col__others popularity-col__others--3">

                            <div class="brick-img"><img src="<?= randomPhotoUser($sm['user']['s_gender']); ?>" alt=""></div>

                            <mark class="brick brick--xsm brick--like brick--stroke"><i class="icon icon--white ion-heart" style="font-size: 17px"></i></mark>

                        </div>

                    </div>

                </div>

            </div>

            <div class="popularity-line js-popularity-promo-block" data-popularity-promo-block-type="9">

                <div class="left popularity-col">

                    <h1 class="popularity-col__title"><?= $sm['lang'][514]['text']; ?>!</h1>

                    <p> <?= $sm['user']['first_name']; ?>, <?= $sm['lang'][515]['text']; ?> <?= $sm['user']['city']; ?> <?= $sm['lang'][516]['text']; ?>!</p>

                    <div class="btn btn--spotlight" onclick="showSpotlight();"> <span class="btn-txt"><?= $sm['lang'][517]['text']; ?>!</span> </div>

                </div>

                <div class="popularity-col">

                    <div class="popularity-col__img popularity-col__img--spotlight">

                        <div class="popularity-col__shadow_circle"></div>

                        <div class="popularity-col__user-photo_">

                            <div class="brick brick--lg brick--blue brick--hover popularity-col__add">

                                <div class="brick-img"><img src="<?= $sm['user']['profile_photo']; ?>"></div><i class="icon icon--xsm icon--white"></i> </div>



                            <div class="brick brick--lg brick--spotlight brick--outline popularity-col__owner">

                                <div class="brick-img"><img src="<?= $sm['user']['profile_photo']; ?>" alt=""></div>

                            </div>

                            <div class="brick brick--lg popularity-col__others popularity-col__others--1">

                                <div class="brick-img"><img src="<?= randomPhotoUser($sm['user']['s_gender']); ?>"></div>

                            </div>

                            <div class="brick brick--lg popularity-col__others popularity-col__others--2">

                                <div class="brick-img"><img src="<?= randomPhotoUser($sm['user']['s_gender']); ?>"></div>

                            </div>

                            <div class="brick brick--lg popularity-col__others popularity-col__others--3">

                                <div class="brick-img"><img src="<?= randomPhotoUser($sm['user']['s_gender']); ?>"></div>

                            </div>

                            <div class="brick brick--lg popularity-col__others popularity-col__others--4">

                                <div class="brick-img"><img src="<?= randomPhotoUser($sm['user']['s_gender']); ?>"></div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>



            <div class="popularity-line popularity-line--bma">

                <div class="popularity-col popularity-col--sm">

                    <div class="popularity-col__img"> <i class="popularity-icon popularity-icon--phone"><span class="b-link js-get-the-app-popularity"></span></i> </div>

                    <p><?= $sm['lang'][518]['text']; ?> <?= $sm['config']['name']; ?> <?= $sm['lang'][519]['text']; ?></p>

                    <div class="btn btn--sm btn--white" style="display: inline-table;margin-right: 15px;"> <span class="btn-txt"><?= $sm['lang'][520]['text']; ?></span></div>

                    <div class="btn btn--sm btn--white"  style="display: inline-table;margin-right: 15px;"> <span class="btn-txt"><?= $sm['lang'][521]['text']; ?></span></div>

                </div>

                <div class="popularity-col popularity-col--sm">

                    <div class="popularity-col__img">

                        <div class="popularity-col__more-photo">

                            <div class="brick brick--xlg popularity-col__others">

                                <div class="brick-img"><img src="https://badoocdn.com/aco/us1.badoo.com/v2/-/-/i/hotornot_v2/popularity/bma-female-1.6.png" alt=""></div>

                            </div>

                            <div class="brick brick--xlg popularity-col__others">

                                <div class="brick-img"><img src="https://badoocdn.com/aco/us1.badoo.com/v2/-/-/i/hotornot_v2/popularity/bma-male-1.6.png" alt=""></div>

                            </div>

                        </div> <i class="popularity-icon popularity-icon--photo"><span class="b-link" data-control-type="upload-overlay" data-type="add_photos" tabindex="-1"></span></i> </div>

                    <p><?= $sm['lang'][522]['text']; ?>.</p>

                    <div class="btn btn--sm btn--white"> <span class="btn-txt"><?= $sm['lang'][523]['text']; ?></span> <span class="b-link" data-control-type="upload-overlay" data-type="add_photos" tabindex="-1"></span> </div>

                </div>

            </div>

        </div>

    </center></div>



                    </div>

                </div>



        

            </div> 