            <?php 
                  if(siteConfig('wEnabled') == 0){
                    header('Location:'.$sm['config']['site_url']);
                  }
                  $w = getWithdrawPackages();
            ?>
            <script>
            url = "withdraw";
            </script>       
            <div class="col s8 real fix-width-content" id="site-content" >              
                <div class="wall" style="height:100%;"> 
                    <div class="payment-promo__head payment-promo__head--spp boostProfile" style="left:-7%;width:107%">
                        <div class="brick brick--xlg brick--stroke">
                            <div class="brick-img profile-photo" data-src="<?= $sm['user']['profile_photo']; ?>" ></div>
                            <mark class="brick brick--sm" style="background: #fff"><img src="<?= $sm['config']['theme_url']; ?>/images/coin.png" /> </mark>
                        </div>
                    </div>                       
                    <div class="payment-promo" style="margin-top: 40px;">
                    <div class="payment-promo__content">

                        <center>            
                        <h5 class="comforta"><?= $sm['lang'][559]['text']; ?></h5><br>
                        <p class="payment-promo__txt" style="margin:0 10% 0 10%;text-align: left;color:#555 ">
                            <?= $sm['lang'][560]['text']; ?> <b>PayPal</b> <?= $sm['lang'][561]['text']; ?> <b><?= $sm['config']['name']; ?></b>.<br><br>
                            <?= $sm['lang'][544]['text']; ?> <b>Paypal</b> <?= $sm['lang'][562]['text']; ?> <b><?= $sm['config']['name']; ?></b> <?= $sm['lang'][563]['text']; ?> 
                            <b><?= siteConfig('wTime'); ?></b> <?= $sm['lang'][564]['text']; ?>.<br><br>
                            <?= $sm['lang'][565]['text']; ?>. <b>$<?= $w[0]['price']; ?></b>.<br><br>
                            <?= $sm['lang'][566]['text']; ?> <b>$<?= $w[0]['price']; ?> (<?= $sm['config']['currency']; ?>)</b> <?= $sm['lang'][567]['text']; ?> <?= $sm['config']['name']; ?> <?= $sm['lang'][568]['text']; ?>.<br>
                        </p>
                        <br>
                       <?php if(checkWithdrawExist() == 1){ ?>
                            <div style="margin:0 10% 0 10%;background:#6301CA;color: #fff;border-radius: 5px;padding:10px;">
                                <strong><?= $sm['lang'][542]['text']; ?></strong><br>
                                <?= $sm['lang'][543]['text']; ?> <?= $sm['user']['paypal'];?>
                            </div>
                        <?php } else { ?>                          
                            <div class="btn  boostProfile" onclick="showWithdraw();"> <span class="btn-txt"><?= $sm['lang'][569]['text']; ?></span></div></center>
                        <?php } ?>
                    </div>
                    <br><br><br>
                  
                    <div class="payment-promo__content" style="padding-bottom: 50px;background: #fafafa;border-radius: 10px;margin: 40px;padding-top: 25px;"><center>            
                        <h5 class="comforta">FAQ</h5><br>

                        <p class="payment-promo__txt" style="margin:0 10% 0 10%;text-align: left;color:#555 ">
<b><?= $sm['lang'][570]['text']; ?></b><br>
<b><?= $sm['config']['name']; ?></b> <?= $sm['lang'][571]['text']; ?>.<br><br>

<b><?= $sm['lang'][572]['text']; ?></b><br>
<?= $sm['lang'][573]['text']; ?>.<br><br>

<b><?= $sm['lang'][574]['text']; ?></b><br>
<?= $sm['lang'][575]['text']; ?> <b><?= $sm['config']['name']; ?></b> <?= $sm['lang'][576]['text']; ?> <?= siteConfig('wTime'); ?> <?= $sm['lang'][577]['text']; ?>.<br><br>

<b><?= $sm['lang'][578]['text']; ?></b><br>
<b><?= $sm['config']['name']; ?></b> <?= $sm['lang'][579]['text']; ?> <b><?= $sm['config']['name']; ?></b> credits-to-<?= $sm['config']['currency']; ?> <?= $sm['lang'][580]['text']; ?>.<br><br>
                        </p>
                        <br></center>                      
                    </div>

                    </div>
                    </div>
                </div>
        
