<!DOCTYPE html>
<html>
<head>
<title><?php echo $sm['config']['title']; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
<meta name="description" content="<?php echo $sm['config']['description']; ?>">
<meta name="keywords" content="<?php echo $sm['config']['keywords']; ?>">
<meta name="author" content="<?php echo $sm['config']['name']; ?>">
<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700,500&amp;subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url']; ?>/css/sweetalert.css">
<link href="https://fonts.googleapis.com/css?family=Comfortaa:400,700" rel="stylesheet">
<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/css/style.css" type="text/css" media="screen, projection" />
<style>
.comforta{
    font-family: "Comfortaa" !important;
}
.shado{
    text-shadow: 0px 3px 2px rgba(0, 0, 0, 0.30);
}
</style>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&key=<?= siteConfig('google_maps'); ?>">
</script>
    <?php
    function getSiteLangsLanding1($start,$finish){
        global $mysqli,$sm;
        $ret = '';
        $query = $mysqli->query("SELECT * FROM languages where visible = 1 ORDER BY id ASC LIMIT $start,$finish");
        if($query->num_rows >= 1) {
            while($result = $query->fetch_object()){
                $ret.='<li><a data-lang="'.$result->id.'" href="javascript:;">'.$result->name.'</a></li>';    
            }
        }
        return $ret;    
    }
    $sm['genders'] = siteGenders($sm['config']['lang']);
    $location = json_decode(file_get_contents('http://freegeoip.net/json/'.$_SERVER['REMOTE_ADDR']));
    $site_config = json_encode($sm['config']);
    $site_lang = json_encode($sm['lang']);
    $user_info = json_encode($sm['user']);
    $filter_age = 0;
    echo 
    '<script>
    var url;
    var mobile = false;     
    var site_config = '. $site_config  . ';
    var site_lang = '. $site_lang  . ';
    var user_info = '. $user_info  . ';
    function request_source(){
        return \'' . $sm['config']['ajax_path'] . '\';
    }
    function site_title(){
        return \'' . $sm['config']['title'] . '\';
    }   
    function theme_source(){
        return \'' . $sm['config']['theme_url'] . '\';
    }
    function site_url(){
        return \'' . $sm['config']['site_url'] . '\';
    }   
    function user_id(){
        return \'' . $sm['user']['id'] . '\';
    }
    var current_user_id = 0;
    var user_name;  
    </script>';
    ?>
    <script>
    function detect_device() {
        var w = window,
            d = document,
            e = d.documentElement,
            g = d.getElementsByTagName('body')[0],
            x = w.innerWidth || e.clientWidth || g.clientWidth,
            y = w.innerHeight|| e.clientHeight|| g.clientHeight;
        var isiPhone =      navigator.userAgent.toLowerCase().indexOf("iphone");
        var isiPad =        navigator.userAgent.toLowerCase().indexOf("ipad");
        var isiPod =        navigator.userAgent.toLowerCase().indexOf("ipod");
        var isiAndroid =    navigator.userAgent.toLowerCase().indexOf("android");
        if(isiPhone > -1 || isiPad > -1 || isiPod > -1 || isiAndroid > -1 && mobile == false){
            window.location= '<?= siteConfig('mobile_site');?>';
        }
    }
    detect_device();
    window.onresize = function() {
        var w = window,
            d = document,
            e = d.documentElement,
            g = d.getElementsByTagName('body')[0],
            x = w.innerWidth || e.clientWidth || g.clientWidth,
            y = w.innerHeight|| e.clientHeight|| g.clientHeight;    
        if(x <= 700 && mobile == false){
            window.location= '<?= siteConfig('mobile_site');?>';    
        }
    };
    </script>
</head>
<body style="background: <?= $sm['landing']['background_color']['val']; ?>;color: <?= $sm['landing']['font_color']['val']; ?>">
<header id="header" >
<div class="header-lang-area">
    <ul class="header-lang-list">
        <?= getSiteLangsLanding1(0,6); ?>
    </ul>
</div>
<div class="header-logo">
    <img src="<?php echo $sm['config']['logo']; ?>">
    <strong class="slogan"><?= $sm['lang'][0]['text']; ?></strong>
</div>
<div class="header-sign-area" >
                <ul class="header-signin-list">
            <li><?= $sm['lang'][1000]['text']; ?></li>
            <li><a href="javascript:;" id="signin-btn-top" class="log-tabs header-login-btn" data-id="loginForm"><?= $sm['lang'][1001]['text']; ?></a></li>
        </ul><!-- / nav -->
        </div>
</header><!-- / header -->
<div class="wrapper" >
<div id="login-section" class="login-section" data-scroll="login-section" style="background-image: url('<?= $sm['landing']['background_image']['val']; ?>');">

    <div class="login-section-holder">
        <div class="container">
            <div class="login-section-intro mantra">
                <h2 class="login-section-title comforta shado"> <?php echo $sm['config']['name']; ?> <?= $sm['lang'][1002]['text']; ?>.</h2>
                  <p><?= $sm['lang'][1003]['text']; ?>.</p>
            </div>
            <div class="login-section-loginbox">
                    <div class="loginbox-tabset">
                        <a class="log-tabs loginForm" data-lid="1" data-id="loginForm"><?= $sm['lang'][13]['text']; ?></a>
                        <a class="log-tabs regForm active" data-lid="2" data-id="regForm"><?= $sm['lang'][8]['text']; ?></a>
                    </div>
                    <div class="loginbox-tab-container">
                        <div id="regForm" class="loginbox-tab-item form-reg-wrap active" data-lid="1">
                            <form method="post" action="#" id="register" class="r s">
                                    <?php if(siteConfig('fb_app_id') != '' || siteConfig('google_key') != '' || siteConfig('instagram_key') != '') { ?>
                                    <div class="loginbox-title"><?= $sm['lang'][1004]['text']; ?></div> 
                                    <?php } ?>
                                    <ul class="social">
                                        <?php if(siteConfig('fb_app_id') != '') { ?>
                                        <li>
                                            <a class="social-button facebook" href="social.php?page=fb">facebook</a>
                                        </li>
                                         <?php } if(siteConfig('google_key') != '') { ?>
                                        <li>
                                            <a class="social-button gg" href="social.php?page=google">google</a>
                                        </li>
                                        <?php } if(siteConfig('instagram_key') != '') { ?>
                                        <li>
                                            <a class="social-button ig" href="social.php?page=instagram">instagram</a>
                                        </li>
                                        <?php } ?>
                                    </ul>
                                    <div class="loginbox-form-row">
                                        <div class="form-control name">
                                            <input class="u v" id="name" type="text" placeholder="<?= $sm['lang'][27]['text']; ?>" name="name">
                                        </div>
                                        <div class="form-error error_name"></div>
                                    </div>
                                    <div class="loginbox-form-row">
                                        <div class="form-control mail">
                                            <input type="text" id="email" placeholder="<?= $sm['lang'][10]['text']; ?>" name="email">
                                        </div>
                                        <div class="form-error error_email"></div>
                                    </div>
                                    <div class="loginbox-form-row">
                                        <div class="form-control pass">
                                            <input type="password" id="pass" placeholder="<?= $sm['lang'][11]['text']; ?>" name="pass">
                                        </div>
                                        <div class="form-error error_password"></div>
                                    </div>
                                    <div class="loginbox-two-column-row">
                                        <div class="loginbox-two-column-item" style="width: 23%">
                                            <div class="form-control age">
                                                <select name="day"  id="day" required>
                                                    <option value="1" disabled selected hidden><?= $sm['lang'][272]['text']; ?></option>
                                                    <?= date_dropdown_landing(1); ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="loginbox-two-column-item" style="width: 46%">
                                            <div class="form-control age">
                                                <select name="month"  id="month" required>
                                                    <option value="1" disabled selected hidden><?= $sm['lang'][273]['text']; ?></option>
                                                    <?= date_dropdown_landing(0,1); ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="loginbox-two-column-item" style="width: 23%">
                                            <div class="form-control age" >
                                                <select name="year" id="year" required >
                                                    <option value="1990" disabled selected hidden><?= $sm['lang'][274]['text']; ?></option>                         
                                                    <?= date_dropdown_landing(0,0,1); ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="loginbox-form-row">
                                        <div class="form-control mail">
                                            <input type="text" id="loc" placeholder="<?= $sm['lang'][33]['text']; ?>" name="loc">
                                        </div>
                                        <div class="form-error error_email"></div>
                                    </div>
                                    <div class="loginbox-two-column-row">
                                        <div class="loginbox-two-column-item">
                                            <div class="form-control gender">
                                                <select name="gender" style="cursor:pointer;" id="gender" placeholder="<?= $sm['lang'][31]['text']; ?>">

                                                    <?php
                                                        foreach($sm['genders'] as $entry){
                                                            echo '<option value="'.$entry['id'].'" style="color:#000;">
                                                            '.$sm['lang'][529]['text'].' '.$entry['text'].'</option>';
                                                        }
                                                    ?>
                                                </select>
                                                <div class="form-error error_gender"></div>
                                            </div>
                                        </div>
                                        <div class="loginbox-two-column-item">
                                            <div class="form-control age">
                                                <select name="looking" style="cursor:pointer;" id="looking" placeholder="<?= $sm['lang'][31]['text']; ?>">
                                                    <?php
                                                        foreach($sm['genders'] as $entry){
                                                            echo '<option value="'.$entry['id'].'" style="color:#000;">
                                                            '.$sm['lang'][530]['text'].' '.$entry['text'].'</option>';
                                                        }
                                                    ?>
                                                </select>
                                                <div class="form-error error_gender"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <input type="hidden" value="register" name="action" />
                                    <input type="hidden" name="city" id="locality" />
                                    <input type="hidden" name="country" id="country"  />
                                    <input type="hidden" name="lat" id="lat" />
                                    <input type="hidden" name="lng" id="lng"  /> 
                                    <!--                                   
                                    <div style="margin-bottom:15px; overflow: hidden; background-color: #F9F9F9; height: 76px;"><script src="https://www.google.com/recaptcha/api.js" async defer></script><div class="g-recaptcha" data-sitekey="6LesJDcUAAAAAFi4q41ha903cTfSrsX308gKj5K5"></div></div>-->
                                    <button class="log-btn green" id="create-acc" type="submit"><?= $sm['lang'][8]['text']; ?></button>
                                    <div class="loginbox-note">                                 <?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 



                                    <a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a>
                                    </div>
                                </form>
                        </div><!-- / regForm -->
                        <div id="forgetForm" class="loginbox-tab-item form-reg-wrap" data-lid="3" style="display: none">
                            <span id="success"></span>
                            <form method="post" action="#" id="recover" class="ag s">
                                    <?php if(siteConfig('fb_app_id') != '' || siteConfig('google_key') != '' || siteConfig('instagram_key') != '') { ?>
                                    <div class="loginbox-title"><?= $sm['lang'][1004]['text']; ?></div> 
                                    <?php } ?>
                                    <ul class="social">
                                        <?php if(siteConfig('fb_app_id') != '') { ?>
                                        <li>
                                            <a class="social-button facebook" href="social.php?page=fb">facebook</a>
                                        </li>
                                         <?php } if(siteConfig('google_key') != '') { ?>
                                        <li>
                                            <a class="social-button gg" href="social.php?page=google">google</a>
                                        </li>
                                        <?php } if(siteConfig('instagram_key') != '') { ?>
                                        <li>
                                            <a class="social-button ig" href="social.php?page=instagram">instagram</a>
                                        </li>
                                        <?php } ?>
                                    </ul>

                                <input type="hidden" value="recover" name="action" />
                                <div class="loginbox-form-row">
                                    <div class="form-control mail">
                                        <input class="txt" type="email" name="recover_email" id="recover_email" required placeholder="<?= $sm['lang'][10]['text']; ?>">
                                    </div>
                                    <div class="form-error error_email error" id="recover-error"></div>
                                </div>
                                <button class="log-btn green" id="recover-now" type="submit"><?= $sm['lang'][15]['text']; ?></button>
                            </form>
                        </div>
                        <div id="loginForm" class="loginbox-tab-item form-reg-wrap" data-lid="2">
                            <span id="success"></span>
                            <form method="post" action="#" id="login" class="ag s">
                                    <?php if(siteConfig('fb_app_id') != '' || siteConfig('google_key') != '' || siteConfig('instagram_key') != '') { ?>
                                    <div class="loginbox-title"><?= $sm['lang'][1004]['text']; ?></div> 
                                    <?php } ?>
                                    <ul class="social">
                                        <?php if(siteConfig('fb_app_id') != '') { ?>
                                        <li>
                                            <a class="social-button facebook" href="social.php?page=fb">facebook</a>
                                        </li>
                                         <?php } if(siteConfig('google_key') != '') { ?>
                                        <li>
                                            <a class="social-button gg" href="social.php?page=google">google</a>
                                        </li>
                                        <?php } if(siteConfig('instagram_key') != '') { ?>
                                        <li>
                                            <a class="social-button ig" href="social.php?page=instagram">instagram</a>
                                        </li>
                                        <?php } ?>
                                    </ul>
                                <input type="hidden" value="login" name="action" />
                                <div class="loginbox-form-row">
                                    <div class="form-control mail">
                                        <input class="txt" type="email" name="login_email" id="login_email" required placeholder="<?= $sm['lang'][10]['text']; ?>">
                                    </div>
                                    <div class="form-error error_email"></div>
                                </div>
                                <div class="loginbox-form-row">
                                    <div class="form-control pass">
                                        <input class="txt" type="password" name="login_pass" id="login_pass" required placeholder="<?= $sm['lang'][11]['text']; ?>"  >
                                    </div>
                                    <div class="form-error error_pass"></div>
                                </div>
                                <button class="log-btn green" id="login-now" type="submit"><?= $sm['lang'][13]['text']; ?></button>
                                <a href="javascript:;" class="user-recovery-pass" id="recover-pwd"><?= $sm['lang'][12]['text']; ?></a>
                            </form>
                        </div>                        
                    </div>
                </div>
        </div>
    </div>

</div>
<div class="stats-section container" data-scroll="stats-section" >
    <div class="stats-section-intro">
        <h2 class="heading" style="color: <?= $sm['landing']['font_color']['val']; ?>"><?= $sm['lang'][1005]['text']; ?></h2>
        <p><?= $sm['lang'][1006]['text']; ?></p>
    </div>
    <div class="stats-column" >
        <div class="stats-column-item">
            <div class="stats-value-box" style="background: #5D06B5">
                <?php $total = 1517620; $real = getTotalUsers(1); $total = $total + $real; ?> 
                <span ><?= number_format($total); ?></span>
            </div>
            <div class="stats-title"><?= $sm['lang'][1007]['text']; ?></div>
        </div>
    </div>
</div>
<div class="two-column-section sympaty-section container" data-scroll="sympaty-section">
    <div class="two-column-section-item">
        <div class="sympaty-visual">
            <div class="sympaty-visual-photo left">
                <img src="<?php echo $sm['config']['theme_url_landing']; ?>/img/sympaty-photo-02.png" alt="sympaty">
            </div>
            <div class="sympaty-visual-photo center">
                <img src="<?php echo $sm['config']['theme_url_landing']; ?>/img/sympaty-photo-03.png" alt="sympaty">
            </div>
            <div class="sympaty-visual-photo right">
                <img src="<?php echo $sm['config']['theme_url_landing']; ?>/img/sympaty-photo-01.png" alt="sympaty">
            </div>
            <div class="sympaty-button">
                <img src="<?php echo $sm['config']['theme_url_landing']; ?>/img/sympaty-buttons.png" alt="sympaty-buttons">
            </div>
        </div>
    </div>
    <div class="two-column-section-item description">
        <h3 class="subheading" style="color: <?= $sm['landing']['font_color']['val']; ?>"><?= $sm['lang'][1008]['text']; ?></h3>
        <p><?= $sm['lang'][1009]['text']; ?></p>
    </div>
</div>
<div class="two-column-section radar-section container" data-scroll="radar-section">
    <div class="two-column-section-item description">
        <h3 class="subheading" style="color: <?= $sm['landing']['font_color']['val']; ?>"><?= $sm['lang'][1010]['text']; ?></h3>
        <p><?= $sm['lang'][1011]['text']; ?></p>
    </div>
    <div class="two-column-section-item">
        <div class="radar-visual" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/map.jpg);">
            <div class="radar-visual-photo photo-01" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/radar-photo-01.png);"></div>
            <div class="radar-visual-photo photo-02" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/radar-photo-02.png);"></div>
            <div class="radar-visual-photo photo-03" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/radar-photo-03.png);"></div>
            <div class="radar-visual-photo photo-04" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/radar-photo-04.png);"></div>
            <div class="radar-visual-photo photo-05" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/radar-photo-05.png);"></div>
            <div class="radar-visual-photo photo-06" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/radar-photo-06.png);"></div>
            <div class="radar-visual-photo photo-07" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/radar-photo-07.png);"></div>
            <div class="radar-visual-photo photo-08" style="background-image: url(<?php echo $sm['config']['theme_url_landing']; ?>/img/radar-photo-08.png);"></div>
        </div>
    </div>
</div>
<div class="app-section container" style="margin-bottom: 140px;margin-top:60px">
    <div class="app-section-intro">
        <h3 class="heading" style="color: <?= $sm['landing']['font_color']['val']; ?>"><?= $sm['lang'][1012]['text']; ?></h3>
        <p><?= $sm['lang'][1013]['text']; ?>.</p>
    </div>
    <div class="app-section-buttons" style="margin-bottom: 45px">
        <a href="<?= $app_android; ?>" class="app-section-btn gplay">
            <img src="<?php echo $sm['config']['theme_url_landing']; ?>/img/button_playstore.png" alt="Google Play">
        </a>
        <a href="<?= $app_ios; ?>" class="app-section-btn appstore">
            <img src="<?php echo $sm['config']['theme_url_landing']; ?>/img/button_appstore.png" alt="Appstore">
        </a>
    </div>
</div>
<footer id="footer" class="footer-small">
    <div class="foot-wr">
        <div class="container">
            <ul class="footer-nav">                
                <li><a href="#">Copyright <?= $sm['config']['name']; ?></a></li>
                <li><a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" target="_blank"><?= $sm['lang'][43]['text']; ?></a></li>
                <li><a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" target="_blank"><?= $sm['lang'][45]['text']; ?></a></li>
                <li><a href="mailto:<?= $sm['config']['email']; ?>"><?= $sm['lang'][64]['text']; ?></a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/jquery.min.js"></script>
<script src="<?php echo $sm['config']['theme_url']; ?>/js/sweetalert.min.js"></script> 
<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/init.js"></script>
<script>
$(window).load(function() {
    function l() {
        var e = window.pageYOffset || document.body.scrollTop,
            t = parseInt(g.height(), 0),
            a = parseInt(f.height(), 0),
            o = parseInt(y.height(), 0),
            l = parseInt(p.height(), 0);
        e >= t - 51 ? m.addClass("scrolled") : m.removeClass("scrolled"), e >= t + a ? y.addClass("scrolled") : y.removeClass("scrolled"), e >= t + a + o? p.addClass("scrolled") : p.removeClass("scrolled")
    }
    var m = $('#header'),
        g = $("[data-scroll=login-section]"),
        f = $("[data-scroll=stats-section]"),
        y = $("[data-scroll=sympaty-section]"),
        p = $("[data-scroll=radar-section]");
    l(), window.addEventListener("scroll", l);

    function e(e) {
        var o = e.currentTarget || e.target,
            l = o.getAttribute("data-id"),
            r = document.querySelectorAll('[data-id="' + l + '"]');
        t(), document.getElementById(l).style.display = "block";
        if(l == 'loginForm'){
            $('.loginForm').addClass('active');
            $('.regForm').removeClass('active');
        } else {
            $('.loginForm').removeClass('active');
            $('.regForm').addClass('active');            
        }
    }
    function t() {
        $('[data-lid]').removeClass("active");
        $('#regForm').removeClass("active");
        $('#loginForm').removeClass("active");
        $('#regForm').hide();
        $('#loginForm').hide();
        $('#forgetForm').hide();
    }   
    $('#recover-pwd').click(function(){
        $('#regForm').hide();
        $('#loginForm').hide();
        $('#forgetForm').show();
    })
    var d = document.querySelectorAll(".log-tabs");
    [].forEach.call(d, (function(t) {
        t.onclick = e
    }));    
});

</script>
</body>
</html>