<?php 
if(!empty($_GET['id'])){
	$usid = secureEncode($_GET['id']);	
	getUserInfo($usid,1);
}
if($sm['profile'] == ''){
	getUserLC($sm['user']['id']);	
}
$profile_info = json_encode($sm['profile']);
$check = blockedUser($sm['user']['id'],$sm['profile']['id']);
if($check == 1){
	header('Location:'.$sm['config']['site_url']);
}
$me = false;
if($sm['user']['id'] == $sm['profile']['id']) { 
	$me = true; 
} else {
	visit($sm['user']['id'],$sm['profile']['id']);
}
$fan = isFan($sm['user']['id'],$sm['profile']['id']);
$me = false;
if($sm['user']['id'] == $sm['profile']['id']) $me = true;		
echo 
'<script>
current_user_id = ' . $sm['profile']['id'] .';
var profile_info = '. $profile_info  . ';	
url = "chat";
</script>';
?>
<?php if(!$me){ ?>
	<?php if($fan == 1){ ?>
		<img class="like-top" src="<?= $sm['config']['theme_url']; ?>/images/liked.jpg">
		<img class="nolike-top" src="<?= $sm['config']['theme_url']; ?>/images/noliked.jpg"/>
	<?php } else { ?>
		<img class="like-top" src="<?= $sm['config']['theme_url']; ?>/images/like.jpg" data-id="<?=$sm['profile']['id']; ?>">
		<img class="nolike-top" src="<?= $sm['config']['theme_url']; ?>/images/nolike.jpg" data-id="<?=$sm['profile']['id']; ?>"/>	
	<?php } ?>
	<h2 onclick="goToProfile(<?=$sm['profile']['id']; ?>)" style="cursor:pointer;">
		<?= $sm['profile']['name']; ?>, <?= $sm['profile']['age']; ?>
		<?php if($sm['profile']['premium'] == 1){
			echo '<div class="premium" data-tooltip="'.$sm['lang'][438]['text'].'"><i class="mdi-editor-attach-money"></i></div>';
		}?>
		<?php if($sm['profile']['verified'] == 1){
			echo '<div class="verified" data-tooltip="'.$sm['lang'][439]['text'].'"><i class="mdi-action-verified-user"></i></div>';
		}?>
		<?php if($sm['profile']['popular'] >= siteConfig('popular_user')){
			echo '<div class="popular" data-tooltip="'.$sm['lang'][440]['text'].'"><i class="mdi-social-whatshot"></i></div>';
		}?>				
	</h2>
	<?  if($sm['profile']['status'] == 'y'){
		echo '<span style="color:#17D42B">'.$sm['lang'][441]['text'].'</span>';
	} else {
		echo '<span>Last connection '.time_elapsed_string($sm['profile']['last_access']).'</span>';
	} ?>
<?php } else { ?>
	<h2 style="left: 20px;">
		<?= $sm['profile']['name']; ?>, <?= $sm['profile']['age']; ?>
		<?php if($sm['profile']['premium'] == 1){
			echo '<div class="premium" data-tooltip="'.$sm['lang'][438]['text'].'"><i class="mdi-editor-attach-money"></i></div>';
		}?>
		<?php if($sm['profile']['verified'] == 1){
			echo '<div class="verified" data-tooltip="'.$sm['lang'][439]['text'].'"><i class="mdi-action-verified-user"></i></div>';
		}?>
		<?php if($sm['profile']['popular'] >= siteConfig('popular_user')){
			echo '<div class="popular" data-tooltip="'.$sm['lang'][440]['text'].'"><i class="mdi-social-whatshot"></i></div>';
		}?>	
	</h2>
	<?  if($sm['profile']['status'] == 'y'){
		echo '<span style="left:22px;color:#17D42B">'.$sm['lang'][441]['text'].'</span>';
	} else {
		echo '<span style="left:22px;">Last connection '.time_elapsed_string($sm['profile']['last_access']).'</span>';
	} ?>
<?php } ?>