                <script> noChat = true; </script>
                <div class="col s8 real fix-width-content" id="site-content"> 
                <div class="profile-menu ">
                  <div style="position: relative;display: inline-table;width: 24.5%;">
	                <center><span class="comforta" style="color: #fff;top:15px;font-size:18px;"><?= $sm['lang'][534]['text']; ?></span></center>               	
                  </div>
                  <div style="position: relative;display: inline-table;width: 24.5%;margin-top:20px;">
	                <center><span class="comforta" style="color: #fff;font-size:18px;"><?= $sm['lang'][295]['text']; ?></span></center>
                  </div>
                  <div style="position: relative;display: inline-table;width: 24.5%;">
	                <center><span class="comforta" style="color: #fff;top:15px;font-size:18px;"><?= $sm['lang'][101]['text']; ?></span></center>
                  </div>

                  <div style="position: relative;display: inline-table;width: 24.5%;">
	                <center><span class="comforta" style="color: #fff;top:15px;font-size:18px;"><?= $sm['lang'][105]['text']; ?></span></center>                	
                  </div>                                                                                           	
                </div>                
                <div class="wall" style="min-height: 550px" >


                	
                  <div style="position: relative;display: inline-table;width: 24.5%;max-height: 540px;overflow-y: scroll;">                    		
			    	  <ul class="list">
			    	  	<?php 
			    	  	$url = $sm['config']['site_url'].'requests/api.php?action=getMatches&id='.$sm['user']['id'];
						$curl_options = array(
		                    CURLOPT_URL => $url,
		                    CURLOPT_RETURNTRANSFER => TRUE,
			            );
			            $ch = curl_init();
			            curl_setopt_array( $ch, $curl_options );
			            $output = curl_exec( $ch );
			            curl_close($ch);
						$arr = json_decode($output,true);	

			    	  	$url = $sm['config']['site_url'].'requests/api.php?action=getChat&id='.$sm['user']['id'];
						$curl_options = array(
		                    CURLOPT_URL => $url,
		                    CURLOPT_RETURNTRANSFER => TRUE,
			            );
			            $ch = curl_init();
			            curl_setopt_array( $ch, $curl_options );
			            $output = curl_exec( $ch );
			            curl_close($ch);
						$lastm = json_decode($output,true);								   	  	 
						foreach ($lastm['matches'] as $val) { ?>
							<li class="list-item">
						      <div>
						        <img src="<?= $val['photo'];?>" class="list-item-image">
						      </div>
						      <div class="list-item-content">
						        <h4><?= $val['firstName'];?></h4>
						        <p><?= $val['last_m'];?></p>
						      </div>
						    </li>
						<?php } ?>
					  </ul>
				  </div>
                  <div style="position: relative;display: inline-table;width: 24.5%;max-height: 540px;overflow-y: scroll;">                    		
			    	  <ul class="list">
						<?php 
						foreach ($arr['mylikes'] as $val) { ?>
							<li class="list-item">
						      <div>
						        <img src="<?= $val['photo'];?>" class="list-item-image">
						      </div>
						      <div class="list-item-content">
						        <h4><?= $val['firstName'];?></h4>
						        <p><?= $val['last_m'];?></p>
						      </div>
						    </li>
						<?php } ?>			    	  	
					  </ul>
				  </div>
                  <div style="position: relative;display: inline-table;width: 24.5%;max-height: 540px;overflow-y: scroll;">                    		
			    	  <ul class="list">
						<?php 
						foreach ($arr['myfans'] as $val) { ?>
							<li class="list-item">
						      <div>
						        <img src="<?= $val['photo'];?>" class="list-item-image">
						      </div>
						      <div class="list-item-content">
						        <h4><?= $val['firstName'];?></h4>
						        <p><?= $val['last_m'];?></p>
						      </div>
						    </li>
						<?php } ?>
					  </ul>
				  </div>
                  <div style="position: relative;display: inline-table;width: 24.5%;max-height: 540px;overflow-y: scroll;">                    		

				  </div>				  				  				  


				  <div class="footer-badoo" style="margin-top:55px;left:-4.15%;width:104%">
						<center>
					<div class="ad-zone">
						<?php echo siteConfig('ads'); ?>
					</div>
					<div class="download-apps">
						<h3><?= $sm['lang'][434]['text']; ?>:</h3>
						<a href="<?php echo $app_ios; ?>">
							<img src="<?php echo $sm['config']['theme_url']; ?>/images/ios.png" />
							<h2><?= $sm['lang'][435]['text']; ?></h2>
						</a>
						<a href="<?php echo $app_android; ?>">
							<img src="<?php echo $sm['config']['theme_url']; ?>/images/android.png" /><h2><?= $sm['lang'][436]['text']; ?></h2>
						</a>
					</div>
					<div class="bottom-left">
						<a href="<?php echo $sm['config']['site_url']; ?>/terms"><h3><?= $sm['lang'][437]['text']; ?></h3></a> <a href="<?php echo $sm['config']['site_url']; ?>/privacy"><h3><?= $sm['lang'][63]['text']; ?></h3></a> <a href="mailto:<?php echo $sm['config']['email']; ?>"><h3><?= $sm['lang'][64]['text']; ?></h3></a> <h3>  <?php echo $sm['config']['name']; ?> 2017 </h3>
					</div>			
				</center>

				  </div>

                </div>






