      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Mobile apps settings
          </h1>
        </section>
    <script>aurl = 'apps';</script>
        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Apps Settings</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="#" id="app-settings">
        <input type="hidden" value="apps" name="action" />
                  <div class="box-body">
                    <div class="form-group"  style="background:#333;padding:15px;">
            <img src="<?php echo appConfig('logo_login'); ?>" style="max-width:150px;" />
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Login App logo</label>
            <input class="form-control" value="<?php echo appConfig('logo_login'); ?>" name="app_logo_login" />
                    </div>
                    <div class="form-group" style="padding:15px;">
            <img src="<?php echo appConfig('logo'); ?>" style="max-width:150px;" />
                    </div>          
                    <div class="form-group">
                      <label for="exampleInputEmail1">App header logo</label>
            <input class="form-control" value="<?php echo appConfig('logo'); ?>" name="app_logo" />
                    </div>        
                     
                  </div><!-- /.box-body -->
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update app settings</button>
                  </div>
                </form>
              </div><!-- /.box -->
      </div>
        <!--
            <div class="col-md-6">
            
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Send custmom push notification to your app user ( <?php echo totalAppUsers(); ?> Total users )</h3>
                </div>
                <form role="form" action="#" id="push-settings">
        <input type="hidden" value="push" name="action" />
                  <div class="box-body">  
                    <div class="form-group">
                      <label for="exampleInputEmail1">Push notification image (recomended size 512px 512px)</label>
            <input class="form-control" value="" name="app_push_image" />
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Push notification title</label>
            <input class="form-control" value="" name="app_push_title" />
                    </div>          
                    <div class="form-group">
                      <label for="exampleInputEmail1">Push notification body</label>
            <textarea class="form-control" name="app_push_body" style="height:120px" row="6"></textarea>
                    </div>                      
                  </div>
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Send push notification</button>
                  </div>
                </form>
              </div> 
               -->
      </div>    
    </div>  
  </section>
</div>  