<!DOCTYPE html>
<html>
  <head>
    <title>Belloo | Admin Dashboard</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="themes/default/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <link href="themes/default/admin/css/AdminLTE.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="themes/default/css/sweetalert.css">		
    <link href="themes/default/admin/css/skins/skin-red.css" rel="stylesheet" type="text/css" />
<script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <script src="https://cdn.jsdelivr.net/emojione/3.0.3/lib/js/emojione.min.js"></script>
	<?php
	$site_config = json_encode($sm['config']);
	$site_prices = json_encode($sm['price']);
	$account_basic = json_encode($sm['basic']);
	$account_premium = json_encode($sm['premium']);
	$site_lang = json_encode($sm['lang']);
	$user_info = json_encode($sm['user']);
	$filter_age = 0;
	echo 
	'<script>
	var url;
	var aurl;	
	var site_config = '. $site_config  . ';
	var site_prices = '. $site_prices  . ';
	var account_basic = '. $account_basic  . ';
	var account_premium = '. $account_premium  . ';
	var site_lang = '. $site_lang  . ';
	var user_info = '. $user_info  . ';
	function request_source(){
		return \'' . $sm['config']['ajax_path'] . '\';
	}
	function site_title(){
		return \'' . $sm['config']['title'] . '\';
	}	
	function theme_source(){
		return \'' . $sm['config']['theme_url'] . '\';
	}
	function site_url(){
		return \'' . $sm['config']['site_url'] . '\';
	}	
	function user_id(){
		return \'' . $sm['user']['id'] . '\';
	}
	var current_user_id = 0;
	var user_name;	
	</script>';
	?>	
  </head>
  <body class="login-page" style="background: #b5ccc6 linear-gradient(to bottom, #3f567c, #b5ccc6) no-repeat;" >
    <div class="login-box">
      <div class="login-logo">
        <a href="index.php?page=admin" style="color:#fff"><b><?= $sm['config']['name']; ?></b> Admin </a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <form action="#" id="admin-login" method="post">
		 	<input type="hidden" value="login" name="action" />
          <div class="form-group has-feedback">
            <input type="text" class="form-control" name="login_email" placeholder="Email"/>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" name="login_pass" placeholder="Password"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8"> 
				<div id="error-result"></div>
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" id="admin-login-btn" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div><!-- /.col -->
          </div>
        </form>
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->
	<script src="themes/default/js/jquery-2.1.1.js"></script>
	<script src="themes/default/js/jquery.form.min.js"></script>
	<script src="themes/default/js/materialize.js"></script>
	<script src="themes/default/js/fbphotobox.js"></script>
	<script src="themes/default/js/sweetalert.min.js"></script> 
	<script src="themes/default/js/jquery.preload.js"></script>
	<script src="themes/default/admin/js/admin.js"></script>		
    <script src="themes/default/admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script>
	$('#admin-login').submit(function(e) {
		e.preventDefault();
		var findme = "Error";
		$.ajax({
				data:  $(this).serialize(),
				url:   request_source()+'/user.php',
				type:  'post',
				beforeSend: function () {
					$("#admin-login-btn").html("Working...");
					$('#error-result').hide();
				},			
				success:  function (response) {  	
					if ( response.indexOf(findme) > -1 ) {
						$('#error-result').html(response);
						$('#error-result').fadeIn();
						$("#admin-login-btn").html("Sign In");
					} else {
						 window.location='index.php?page=admin';
					}
				}
		});					
	});
	</script>	
  </body>
</html>