<!doctype html>
	<head>
		<title><?php echo $sm['config']['title']; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
		<meta name="description" content="<?php echo $sm['config']['description']; ?>">
		<meta name="keywords" content="<?php echo $sm['config']['keywords']; ?>">
		<meta name="author" content="<?php echo $sm['config']['name']; ?>">		
		<noscript>		
		<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/css/skel.css" />
		<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/css/style.css" />
		</noscript>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/jquery.min.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/jquery.dropotron.min.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/jquery.scrollgress.min.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/skel.min.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/skel-layers.min.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url']; ?>/css/sweetalert.css">			
		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&key=<?= siteConfig('google_maps'); ?>"></script>
		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Comfortaa:400,700" rel="stylesheet">	
		<?php 
		$sm['genders'] = siteGenders($sm['config']['lang']);
		?>
		<style>
		.comforta{
			font-family: "Comfortaa" !important;
		}
		#preloader {
			position: fixed;
			top:0;
			left:0;
			right:0;
			bottom:0;
			background: #fff;
		  height:100%;
		  width:100%;
			z-index:99; /* makes sure it stays on top */
		}
		#status {
			width:200px;
			height:200px;
			position:absolute;
			left:50%; /* centers the loading animation horizontally one the screen */
			top:50%; /* centers the loading animation vertically one the screen */
			background-image:url(<?php echo $sm['config']['theme_url_landing']; ?>/images/status.gif); /* path to your loading animation */
			background-repeat:no-repeat;
			background-position:center;
			margin:-100px 0 0 -100px; /* is width and height divided by two */
		}
		</style>
		<?php
		$location = json_decode(file_get_contents('http://freegeoip.net/json/'.$_SERVER['REMOTE_ADDR']));
		$site_config = json_encode($sm['config']);
		$site_lang = json_encode($sm['lang']);
		$user_info = json_encode($sm['user']);
		$filter_age = 0;
		echo 
		'<script>
		var url;
		var mobile = false;		
		var site_config = '. $site_config  . ';
		var site_lang = '. $site_lang  . ';
		var user_info = '. $user_info  . ';
		function request_source(){
			return \'' . $sm['config']['ajax_path'] . '\';
		}
		function site_title(){
			return \'' . $sm['config']['title'] . '\';
		}	
		function theme_source(){
			return \'' . $sm['config']['theme_url'] . '\';
		}
		function site_url(){
			return \'' . $sm['config']['site_url'] . '\';
		}	
		function user_id(){
			return \'' . $sm['user']['id'] . '\';
		}
		var current_user_id = 0;
		var user_name;	
		</script>';
		?>
		<script>
		function detect_device() {
			var w = window,
				d = document,
				e = d.documentElement,
				g = d.getElementsByTagName('body')[0],
				x = w.innerWidth || e.clientWidth || g.clientWidth,
				y = w.innerHeight|| e.clientHeight|| g.clientHeight;
			var isiPhone = 		navigator.userAgent.toLowerCase().indexOf("iphone");
			var isiPad = 		navigator.userAgent.toLowerCase().indexOf("ipad");
			var isiPod = 		navigator.userAgent.toLowerCase().indexOf("ipod");
			var isiAndroid = 	navigator.userAgent.toLowerCase().indexOf("android");
			if(isiPhone > -1 || isiPad > -1 || isiPod > -1 || isiAndroid > -1 && mobile == false){
				window.location= '<?= siteConfig('mobile_site');?>';
			}
		}
		detect_device();
		window.onresize = function() {
			var w = window,
				d = document,
				e = d.documentElement,
				g = d.getElementsByTagName('body')[0],
				x = w.innerWidth || e.clientWidth || g.clientWidth,
				y = w.innerHeight|| e.clientHeight|| g.clientHeight;	
			if(x <= 700 && mobile == false){
				window.location= '<?= siteConfig('mobile_site');?>';	
			}
		};
		</script>		
	</head>
	<body class="landing">
			<div id="preloader">
				<div id="status">&nbsp;</div>
			</div>	
			<header id="header" class="alt">		
				<nav id="nav">
				  <ul>
						<li>
							<a href="javascript:;" class="icon fa-angle-down"><span class="icon fa-globe"></span></a>
							<ul> 
                            <table>
                            <tr>
								<?= getSiteLangsIndex(0,6); ?>                          
                            </tr>
								<?= getSiteLangsIndex(6,6); ?>  
                            <tr>                        
                            </tr>
								<?= getSiteLangsIndex(12,6); ?>
                            <tr>                           
                            </tr>
								<?= getSiteLangsIndex(18,6); ?>
                            <tr>                          
                            </tr> 
								<?= getSiteLangsIndex(24,6); ?>
                            <tr>                          
                            </tr>
								<?= getSiteLangsIndex(30,6); ?>
                            <tr>                           
                            </tr>
								<?= getSiteLangsIndex(36,6); ?>
                            <tr>                           
                            </tr>
								<?= getSiteLangsIndex(42,6); ?>
                            <tr>                          
                            </tr>  
                            </table>                           
                       		</ul>
						</li>						
						<li><a href="javascript:;" data-login="true" class="button special"><?= $sm['lang'][1]['text']; ?></a></li>
					</ul>
				</nav>
			</header>
			<div class="main">
				<div class="circle"></div><div class="circle"></div><div class="circle"></div><div class="circle"></div><div class="circle"></div><div class="circle"></div>
				<div class="left">
					<div class="header-text">
						<center><img src="<?php echo $sm['config']['logo_landing']; ?>" width="180px"  style="position: absolute;left:0;top:-60px;">
						</center>
						<h1 class="comforta" style="color: #666"><?= $sm['lang'][0]['text']; ?></h1>
						<h1 class="comforta"><b><?= $location->city; ?></b></h1>
					</div>
					<div class="sub-text">
						<p><?= $sm['lang'][21]['text']; ?></p>
					</div>
					<div class="latest-users">
						<?= getLatestUsersProfilePhoto(); ?>
					</div>
				</div>
				<div class="right">
					<div class="box">
						<div class="header">
							<? if(siteConfig('fb_app_id') != '') { ?>
							<a href="social.php?page=fb">
								<div class="fb"> 
									<div class="logo">
										<i class="icon fa-facebook"></i>
									</div>
									<h3><? $sign = explode(' ',$sm['lang'][13]['text']); echo $sign[0]; ?></h3>								
								</div>
							</a>
							<? } if(siteConfig('twitter_key') != ''){ ?>
							<a href="social.php?page=twitter">
								<div class="twitter"> 
									<div class="logo">
										<i class="icon fa-twitter"></i>
									</div>
									<h3><? $sign = explode(' ',$sm['lang'][13]['text']); echo $sign[0]; ?></h3>								
								</div>
							</a>
							<? } if(siteConfig('google_key') != '' || siteConfig('instagram_key') != ''){  ?>							
							<div class="more"> 
								<div class="logo">
									<i id="more-icon" class="icon fa-ellipsis-h"></i>
								</div>								
							</div>
							<? } ?>
						</div>
						<div class="socials">
							<ul>
							  <? if(siteConfig('instagram_key') != ''){ ?>
							  <a href="social.php?page=l=instagram">
								<li><img src="<?php echo $sm['config']['theme_url_landing']; ?>/images/insta.jpg">Instagram</li>
							  </a>
							  <? } if(siteConfig('google_key') != ''){  ?>
							  <a href="social.php?page==google">
								<li><img src="<?php echo $sm['config']['theme_url_landing']; ?>/images/google.jpg">Google</li>
							  </a>
							  <? } ?>
							</ul>								
						</div>
						<div id="login-form"  style="display:none;">
							<div class="title">
								<h1 class="comforta"><?= $sm['lang'][380]['text']; ?> <?= $sm['config']['name']; ?></h1>
							</div>
							<div class="form">
								<form method="post" action="#" id="login" style="margin:0;padding:0;">
								<input type="hidden" value="login" name="action" />
								<input type="email" name="login_email" id="login_email" required placeholder="<?= $sm['lang'][10]['text']; ?>" />
								<input type="password" name="login_pass" id="login_pass" required placeholder="<?= $sm['lang'][11]['text']; ?>"  />
								</form>
								<div class="12u 12u(mobilep)" style="text-align:right; font-size:14px; padding-right:40px; color:#888;" >
									<a href="javascript:;" id="recover-pwd"><?= $sm['lang'][12]['text']; ?></a>
								</div>
								<div class="error"  id="login-error"></div>
								<div class="signup" id="login-now"><?= $sm['lang'][13]['text']; ?></div>
								<div class="info">
									<?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 
									<a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a>								
								</div>
							</div>							
						</div>
						<div id="recover-form"  style="display:none;">
							<div class="title">
								<h1><?= $sm['lang'][14]['text']; ?></h1>
							</div>
							<div class="form">
								<form method="post" action="#" id="recover" style="margin:0;padding:0;">
								<input type="hidden" value="recover" name="action" />
								<input type="email" name="recover_email" id="recover_email" required placeholder="<?= $sm['lang'][10]['text']; ?>"  />
								</form>
								<div class="error"  id="recover-error"></div>
								<div class="signup" id="recover-now"><?= $sm['lang'][15]['text']; ?></div>
								<div class="info">
									<?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 
									<a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a>								
								</div>
							</div>							
						</div>						
						<div id="register-form">
							<div class="title">
								<h1><?= $sm['lang'][24]['text']; ?></h1>
							</div>
							<div class="form">
								<form method="post" action="#" id="register" style="margin:0;padding:0;">
								<input type="text"  name="name" maxlength="18" id="name" required placeholder="<?= $sm['lang'][27]['text']; ?>" />
								<input type="email" name="email" required id="email" placeholder="<?= $sm['lang'][10]['text']; ?>"  />
								<input type="password" name="pass" id="pass" required placeholder="<?= $sm['lang'][11]['text']; ?>" />
								<select name="day" id="day" style="width:22%;" required >
									<option value="1" disabled selected hidden ><?= $sm['lang'][272]['text']; ?></option>
									<?= date_dropdown_landing(1); ?>
								</select>
								<select name="month"  id="month"  style="width:32%;margin-left:10px" required>						
									<option value="1" disabled selected hidden><?= $sm['lang'][273]['text']; ?></option>
									<?= date_dropdown_landing(0,1); ?>
								</select>
								<select name="year" id="year" style="width:22%;margin-left:10px" required >
									<option value="1990" disabled selected hidden><?= $sm['lang'][274]['text']; ?></option>							
									<?= date_dropdown_landing(0,0,1); ?>
								</select>
								<input type="text" name="loc" id="loc" required placeholder="<?= $sm['lang'][33]['text']; ?>" />
								<select name="gender" style="cursor:pointer;" id="gender" placeholder="<?= $sm['lang'][31]['text']; ?>">
									<?php
										foreach($sm['genders'] as $entry){
											echo '<option value="'.$entry['id'].'" style="color:#000;">
											'.$sm['lang'][529]['text'].' '.$entry['text'].'</option>';
										}
									?>
								</select>
								<select name="looking" style="cursor:pointer;" id="looking" placeholder="<?= $sm['lang'][31]['text']; ?>">
									<?php
										foreach($sm['genders'] as $entry){
											echo '<option value="'.$entry['id'].'" style="color:#000;">
											'.$sm['lang'][530]['text'].' '.$entry['text'].'</option>';
										}
									?>
								</select>
								<input type="hidden" value="register" name="action" />
								<input type="hidden" name="city" id="locality" />
								<input type="hidden" name="country" id="country"  />
								<input type="hidden" name="lat" id="lat" />
								<input type="hidden" name="lng" id="lng"  />
								</form>
								<div class="error"  id="error"></div>
								<div class="signup" id="create-acc"><?= $sm['lang'][8]['text']; ?></div>
								<div class="info">
									<?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 
									<a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a>								
								</div>
							</div>
						</div>						
					</div>
				</div>
				<?php $total = 1900000; $real = getTotalUsers(1); $total = $total + $real; ?> 
				<div style="position:absolute;bottom:0;left:0;width:100%;padding-top:60px;padding-bottom:20px;">
					<div style="float:left;padding-left:5px;">
						<span style="float:left;margin-left:25px;font-weight:500;font-size:38px;color:#40B800;padding-bottom:10px;"><?= number_format($total); ?></span><br>
						<span style="float:left;margin-left:25px;font-size:20px;color:#40B800;"><?= $sm['lang'][108]['text']; ?></span>
					</div>					
				</div>				
			</div>
		<script src="<?php echo $sm['config']['theme_url']; ?>/js/jquery.preload.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/dynamics.js"></script>		
		<script src="<?php echo $sm['config']['theme_url']; ?>/js/sweetalert.min.js"></script> 		
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/init.js"></script>
		<script type="text/javascript">
		var w = $(window).width();		
		$(window).load(function() {
			var h = $(window).height();	
			$('.main').css('height',h+'px');
			$('#status').fadeOut(); // will first fade out the loading animation
			$('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
			$('body').delay(350).css({'overflow':'visible'});
			$('body').keyup(function(e) {
				switch (e.keyCode) {
					case 13: // Enter
						$('#login-now').click();
					break;
				}
			});
			$('select').change(function(e){
				$(this).css('color','#333');
			});
			$('.more').click(function(e){
				e.preventDefault();
				if($('.socials').css('opacity') == 0){
					show();
					$('#more-icon').removeClass('fa-ellipsis-h');
					$('#more-icon').addClass('fa-close');
				} else {
					hide();
					$('#more-icon').removeClass('fa-close');							
					$('#more-icon').addClass('fa-ellipsis-h');							
				}
			});					
			var nav = document.querySelector('.socials')
			var items = document.querySelectorAll('.socials ul li')
			function show() {
			  // Animate the popover
			  dynamics.animate(nav, {
				opacity: 1,
				scale: 1
			  }, {
				type: dynamics.spring,
				frequency: 200,
				friction: 270,
				duration: 800
			  })
			  // Animate each line individually
			  for(var i=0; i<items.length; i++) {
				var item = items[i]
				// Define initial properties
				dynamics.css(item, {
				  opacity: 0,
				  translateY: 20
				})
				// Animate to final properties
				dynamics.animate(item, {
				  opacity: 1,
				  translateY: 0
				}, {
				  type: dynamics.spring,
				  frequency: 300,
				  friction: 435,
				  duration: 1000,
				  delay: 100 + i * 40
				})
			  }
			}
			function hide() {
			  // Animate the popover
			  dynamics.animate(nav, {
				opacity: 0,
				scale: .1
			  }, {
				type: dynamics.easeInOut,
				duration: 300,
				friction: 100
			  })
			}
		})
		</script> 		
	</body>
</html>