			<script>
			url = "terms";
			</script>            
<div class="col s8 real fix-width-content" id="site-content">           
                <div class="profile-menu ">
                    <ul>
                        <li class="selected" >
                            <?= $sm['lang'][103]['text']; ?>
                        </li>                                     
                    </ul>
                </div>
				
                <div class="wall" > 
					<?= siteConfig('terms'); ?>
                </div>
            </div> 